### ISSUE TITLE
Please help to buil openwrt for r619ac 

### ISSUE THREAD

**Issue by chuc2rk** [KevinMX/openwrt-r619ac-build#1]
Please help me to build openwrt for r619ac, i don't know where to download source. In offical openwrt, i don't find board r619ac.
Thanks in advance!

**Comment by KevinMX** [comment]
This board is only supported in coolsnowwolf/lede by this time.
There's a brief guide in that repo's readme, or just Google it.
If you just need a firmware and do not know how to build the firmware, just go to releases and download one.
